listen_addresses = '*'

shared_buffers = 2GB
work_mem = 64MB
maintenance_work_mem = 512MB
effective_cache_size = 6GB
random_page_cost = 1.1

wal_buffers = 16MB
checkpoint_completion_target = 0.9
max_wal_size = 2GB
min_wal_size = 512MB

max_connections = 100
default_statistics_target = 100

logging_collector = on
log_min_duration_statement = 500
log_line_prefix = '%m [%p] %q%u@%d '
